id: P006781
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25512
  title: ལྐོག་གྱུར་གྱི་འཇིག་རྟེན།
  author: ''
  volumes:
    470e548824034436a4a65960b8811ccf:
      image_group_id: I1KG25514
      title: ''
      volume_number: 1
      total_pages: 174
      base_file: v001.txt
